### ISSUE TITLE
concatenare

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/vettori#18]
concatenare due stringhe

**Comment by FabioZTessitore** [comment]
Crea una stringa di output

**Comment by TeoColuccio** [comment]
Prof l'ho fatto anche questo..

**Comment by FabioZTessitore** [comment]
Ti avevo detto di creare una stringa di output

**Comment by FabioZTessitore** [comment]
può anche andar bene (però non hai usato strcat haha)

**Comment by TeoColuccio** [comment]
Lo posso anche mettere all'interno di sprintf

Il 25 mar 2017 08:37, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

può anche andar bene (però non hai usato strcat haha)

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/Teodoro777/vettori/issues/18#issuecomment-289195785>,
or mute the thread

**Comment by TeoColuccio** [comment]
In teoria dovrebbe funzionare..

**Comment by FabioZTessitore** [comment]
Vabbe'. Avrei voluto una chiamata a strcpy e una a strcat

**Comment by FabioZTessitore** [comment]
Le hai provate tutte tranne quella che volevo. Andiamo avanti

**Comment by TeoColuccio** [comment]
Però modificatela come volevate, per curiosità ahah
